// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#include "onnx_runtime_impl.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `cosmonic:onnx-runtime/types`

__attribute__((__weak__, __export_name__("cabi_post_cosmonic:onnx-runtime/types#create-session")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_create_session_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_cosmonic:onnx-runtime/types#[method]session.run")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_method_session_run_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len = *((size_t*) (arg0 + (2*sizeof(void*))));
      if (len > 0) {
        uint8_t *ptr = *((uint8_t **) (arg0 + sizeof(void*)));
        for (size_t i = 0; i < len; i++) {
          uint8_t *base = ptr + i * (3*sizeof(void*));
          (void) base;
          if ((*((size_t*) (base + sizeof(void*)))) > 0) {
            free(*((uint8_t **) (base + 0)));
          }
        }
        free(ptr);
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_cosmonic:onnx-runtime/types#[method]session.get-inputs")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_method_session_get_inputs_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (3*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + sizeof(void*)))) > 0) {
        free(*((uint8_t **) (base + 0)));
      }
    }
    free(ptr);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_cosmonic:onnx-runtime/types#create-tensor")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_create_tensor_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_cosmonic:onnx-runtime/types#[method]tensor.get-dims")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_method_tensor_get_dims_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 8;
      (void) base;
    }
    free(ptr);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_cosmonic:onnx-runtime/types#[method]tensor.get-data")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_method_tensor_get_data_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 1;
      (void) base;
    }
    free(ptr);
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void exports_cosmonic_onnx_runtime_types_error_free(exports_cosmonic_onnx_runtime_types_error_t *ptr) {
  onnx_runtime_impl_string_free(ptr);
}

void exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_free(exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_t *ptr) {
  if (ptr->is_some) {
  }
}

void exports_cosmonic_onnx_runtime_types_session_options_free(exports_cosmonic_onnx_runtime_types_session_options_t *ptr) {
  exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_free(&ptr->graph_optimization_level);
}

void exports_cosmonic_onnx_runtime_types_option_log_severity_level_free(exports_cosmonic_onnx_runtime_types_option_log_severity_level_t *ptr) {
  if (ptr->is_some) {
  }
}

void onnx_runtime_impl_option_u32_free(onnx_runtime_impl_option_u32_t *ptr) {
  if (ptr->is_some) {
  }
}

void onnx_runtime_impl_option_bool_free(onnx_runtime_impl_option_bool_t *ptr) {
  if (ptr->is_some) {
  }
}

void onnx_runtime_impl_option_string_free(onnx_runtime_impl_option_string_t *ptr) {
  if (ptr->is_some) {
    onnx_runtime_impl_string_free(&ptr->val);
  }
}

void onnx_runtime_impl_tuple2_string_string_free(onnx_runtime_impl_tuple2_string_string_t *ptr) {
  onnx_runtime_impl_string_free(&ptr->f0);
  onnx_runtime_impl_string_free(&ptr->f1);
}

void onnx_runtime_impl_list_tuple2_string_string_free(onnx_runtime_impl_list_tuple2_string_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    onnx_runtime_impl_tuple2_string_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      onnx_runtime_impl_tuple2_string_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_cosmonic_onnx_runtime_types_run_options_free(exports_cosmonic_onnx_runtime_types_run_options_t *ptr) {
  exports_cosmonic_onnx_runtime_types_option_log_severity_level_free(&ptr->log_severity_level);
  onnx_runtime_impl_option_u32_free(&ptr->log_verbosity_level);
  onnx_runtime_impl_option_bool_free(&ptr->terminate);
  onnx_runtime_impl_option_string_free(&ptr->tag);
  onnx_runtime_impl_list_tuple2_string_string_free(&ptr->extra);
}

__attribute__((__import_module__("[export]cosmonic:onnx-runtime/types"), __import_name__("[resource-drop]session")))
extern void __wasm_import_exports_cosmonic_onnx_runtime_types_session_drop(int32_t handle);

void exports_cosmonic_onnx_runtime_types_session_drop_own(exports_cosmonic_onnx_runtime_types_own_session_t handle) {
  __wasm_import_exports_cosmonic_onnx_runtime_types_session_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]cosmonic:onnx-runtime/types"), __import_name__("[resource-new]session")))
extern int32_t __wasm_import_exports_cosmonic_onnx_runtime_types_session_new(int32_t);

__attribute__((__import_module__("[export]cosmonic:onnx-runtime/types"), __import_name__("[resource-rep]session")))
extern int32_t __wasm_import_exports_cosmonic_onnx_runtime_types_session_rep(int32_t);

exports_cosmonic_onnx_runtime_types_own_session_t exports_cosmonic_onnx_runtime_types_session_new(exports_cosmonic_onnx_runtime_types_session_t *rep) {
  return (exports_cosmonic_onnx_runtime_types_own_session_t) { __wasm_import_exports_cosmonic_onnx_runtime_types_session_new((int32_t) rep) };
}

exports_cosmonic_onnx_runtime_types_session_t* exports_cosmonic_onnx_runtime_types_session_rep(exports_cosmonic_onnx_runtime_types_own_session_t handle) {
  return (exports_cosmonic_onnx_runtime_types_session_t*) __wasm_import_exports_cosmonic_onnx_runtime_types_session_rep(handle.__handle);
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#[dtor]session")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_session_dtor(exports_cosmonic_onnx_runtime_types_session_t* arg) {
  exports_cosmonic_onnx_runtime_types_session_destructor(arg);
}

__attribute__((__import_module__("[export]cosmonic:onnx-runtime/types"), __import_name__("[resource-drop]tensor")))
extern void __wasm_import_exports_cosmonic_onnx_runtime_types_tensor_drop(int32_t handle);

void exports_cosmonic_onnx_runtime_types_tensor_drop_own(exports_cosmonic_onnx_runtime_types_own_tensor_t handle) {
  __wasm_import_exports_cosmonic_onnx_runtime_types_tensor_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]cosmonic:onnx-runtime/types"), __import_name__("[resource-new]tensor")))
extern int32_t __wasm_import_exports_cosmonic_onnx_runtime_types_tensor_new(int32_t);

__attribute__((__import_module__("[export]cosmonic:onnx-runtime/types"), __import_name__("[resource-rep]tensor")))
extern int32_t __wasm_import_exports_cosmonic_onnx_runtime_types_tensor_rep(int32_t);

exports_cosmonic_onnx_runtime_types_own_tensor_t exports_cosmonic_onnx_runtime_types_tensor_new(exports_cosmonic_onnx_runtime_types_tensor_t *rep) {
  return (exports_cosmonic_onnx_runtime_types_own_tensor_t) { __wasm_import_exports_cosmonic_onnx_runtime_types_tensor_new((int32_t) rep) };
}

exports_cosmonic_onnx_runtime_types_tensor_t* exports_cosmonic_onnx_runtime_types_tensor_rep(exports_cosmonic_onnx_runtime_types_own_tensor_t handle) {
  return (exports_cosmonic_onnx_runtime_types_tensor_t*) __wasm_import_exports_cosmonic_onnx_runtime_types_tensor_rep(handle.__handle);
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#[dtor]tensor")))
void __wasm_export_exports_cosmonic_onnx_runtime_types_tensor_dtor(exports_cosmonic_onnx_runtime_types_tensor_t* arg) {
  exports_cosmonic_onnx_runtime_types_tensor_destructor(arg);
}

void onnx_runtime_impl_list_u8_free(onnx_runtime_impl_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void exports_cosmonic_onnx_runtime_types_option_session_options_free(exports_cosmonic_onnx_runtime_types_option_session_options_t *ptr) {
  if (ptr->is_some) {
    exports_cosmonic_onnx_runtime_types_session_options_free(&ptr->val);
  }
}

void exports_cosmonic_onnx_runtime_types_result_own_session_error_free(exports_cosmonic_onnx_runtime_types_result_own_session_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    exports_cosmonic_onnx_runtime_types_error_free(&ptr->val.err);
  }
}

void exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_free(exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_t *ptr) {
  onnx_runtime_impl_string_free(&ptr->f0);
}

void exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_free(exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_cosmonic_onnx_runtime_types_option_run_options_free(exports_cosmonic_onnx_runtime_types_option_run_options_t *ptr) {
  if (ptr->is_some) {
    exports_cosmonic_onnx_runtime_types_run_options_free(&ptr->val);
  }
}

void exports_cosmonic_onnx_runtime_types_result_list_tuple2_string_own_tensor_error_free(exports_cosmonic_onnx_runtime_types_result_list_tuple2_string_own_tensor_error_t *ptr) {
  if (!ptr->is_err) {
    exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_free(&ptr->val.ok);
  } else {
    exports_cosmonic_onnx_runtime_types_error_free(&ptr->val.err);
  }
}

void exports_cosmonic_onnx_runtime_types_tuple2_string_tensor_type_free(exports_cosmonic_onnx_runtime_types_tuple2_string_tensor_type_t *ptr) {
  onnx_runtime_impl_string_free(&ptr->f0);
}

void exports_cosmonic_onnx_runtime_types_list_tuple2_string_tensor_type_free(exports_cosmonic_onnx_runtime_types_list_tuple2_string_tensor_type_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_cosmonic_onnx_runtime_types_tuple2_string_tensor_type_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_cosmonic_onnx_runtime_types_tuple2_string_tensor_type_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void onnx_runtime_impl_list_u64_free(onnx_runtime_impl_list_u64_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint64_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void exports_cosmonic_onnx_runtime_types_result_own_tensor_error_free(exports_cosmonic_onnx_runtime_types_result_own_tensor_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    exports_cosmonic_onnx_runtime_types_error_free(&ptr->val.err);
  }
}

void onnx_runtime_impl_string_set(onnx_runtime_impl_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void onnx_runtime_impl_string_dup(onnx_runtime_impl_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void onnx_runtime_impl_string_free(onnx_runtime_impl_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("cosmonic:onnx-runtime/types#create-session")))
uint8_t * __wasm_export_exports_cosmonic_onnx_runtime_types_create_session(uint8_t * arg, size_t arg0, int32_t arg1, int32_t arg2, int32_t arg3) {
  exports_cosmonic_onnx_runtime_types_option_session_options_t option4;
  switch (arg1) {
    case 0: {
      option4.is_some = false;
      break;
    }
    case 1: {
      option4.is_some = true;
      exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_t option;
      switch (arg2) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = arg3;
          break;
        }
      }

      option4.val = (exports_cosmonic_onnx_runtime_types_session_options_t) {
        (exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_t) option,
      };
      break;
    }
  }
  onnx_runtime_impl_list_u8_t arg5 = (onnx_runtime_impl_list_u8_t) { (uint8_t*)(arg), (arg0) };
  exports_cosmonic_onnx_runtime_types_result_own_session_error_t ret;
  exports_cosmonic_onnx_runtime_types_own_session_t ok;
  exports_cosmonic_onnx_runtime_types_error_t err;
  ret.is_err = !exports_cosmonic_onnx_runtime_types_create_session(&arg5, option4.is_some ? &(option4.val) : NULL, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const exports_cosmonic_onnx_runtime_types_error_t *payload6 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload6).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload6).ptr;
  } else {
    const exports_cosmonic_onnx_runtime_types_own_session_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + sizeof(void*))) = (*payload).__handle;
  }
  return ptr;
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#[method]session.run")))
uint8_t * __wasm_export_exports_cosmonic_onnx_runtime_types_method_session_run(uint8_t * arg, uint8_t * arg0, size_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6, int32_t arg7, int32_t arg8, int32_t arg9, uint8_t * arg10, size_t arg11, uint8_t * arg12, size_t arg13) {
  exports_cosmonic_onnx_runtime_types_option_run_options_t option17;
  switch (arg2) {
    case 0: {
      option17.is_some = false;
      break;
    }
    case 1: {
      option17.is_some = true;
      exports_cosmonic_onnx_runtime_types_option_log_severity_level_t option;
      switch (arg3) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = arg4;
          break;
        }
      }
      onnx_runtime_impl_option_u32_t option14;
      switch (arg5) {
        case 0: {
          option14.is_some = false;
          break;
        }
        case 1: {
          option14.is_some = true;
          option14.val = (uint32_t) (arg6);
          break;
        }
      }
      onnx_runtime_impl_option_bool_t option15;
      switch (arg7) {
        case 0: {
          option15.is_some = false;
          break;
        }
        case 1: {
          option15.is_some = true;
          option15.val = arg8;
          break;
        }
      }
      onnx_runtime_impl_option_string_t option16;
      switch (arg9) {
        case 0: {
          option16.is_some = false;
          break;
        }
        case 1: {
          option16.is_some = true;
          option16.val = (onnx_runtime_impl_string_t) { (uint8_t*)(arg10), (arg11) };
          break;
        }
      }

      option17.val = (exports_cosmonic_onnx_runtime_types_run_options_t) {
        (exports_cosmonic_onnx_runtime_types_option_log_severity_level_t) option,
        (onnx_runtime_impl_option_u32_t) option14,
        (onnx_runtime_impl_option_bool_t) option15,
        (onnx_runtime_impl_option_string_t) option16,
        (onnx_runtime_impl_list_tuple2_string_string_t) (onnx_runtime_impl_list_tuple2_string_string_t) { (onnx_runtime_impl_tuple2_string_string_t*)(arg12), (arg13) },
      };
      break;
    }
  }
  exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t arg18 = (exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t) { (exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_t*)(arg0), (arg1) };
  exports_cosmonic_onnx_runtime_types_result_list_tuple2_string_own_tensor_error_t ret;
  exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t ok;
  exports_cosmonic_onnx_runtime_types_error_t err;
  ret.is_err = !exports_cosmonic_onnx_runtime_types_method_session_run(((exports_cosmonic_onnx_runtime_types_session_t*) arg), &arg18, option17.is_some ? &(option17.val) : NULL, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const exports_cosmonic_onnx_runtime_types_error_t *payload19 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload19).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload19).ptr;
  } else {
    const exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#[method]session.get-inputs")))
uint8_t * __wasm_export_exports_cosmonic_onnx_runtime_types_method_session_get_inputs(uint8_t * arg) {
  exports_cosmonic_onnx_runtime_types_list_tuple2_string_tensor_type_t ret;
  exports_cosmonic_onnx_runtime_types_method_session_get_inputs(((exports_cosmonic_onnx_runtime_types_session_t*) arg), &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#create-tensor")))
uint8_t * __wasm_export_exports_cosmonic_onnx_runtime_types_create_tensor(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  onnx_runtime_impl_list_u8_t arg4 = (onnx_runtime_impl_list_u8_t) { (uint8_t*)(arg0), (arg1) };
  onnx_runtime_impl_list_u64_t arg5 = (onnx_runtime_impl_list_u64_t) { (uint64_t*)(arg2), (arg3) };
  exports_cosmonic_onnx_runtime_types_result_own_tensor_error_t ret;
  exports_cosmonic_onnx_runtime_types_own_tensor_t ok;
  exports_cosmonic_onnx_runtime_types_error_t err;
  ret.is_err = !exports_cosmonic_onnx_runtime_types_create_tensor(arg, &arg4, &arg5, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const exports_cosmonic_onnx_runtime_types_error_t *payload6 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload6).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload6).ptr;
  } else {
    const exports_cosmonic_onnx_runtime_types_own_tensor_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + sizeof(void*))) = (*payload).__handle;
  }
  return ptr;
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#[method]tensor.get-dims")))
uint8_t * __wasm_export_exports_cosmonic_onnx_runtime_types_method_tensor_get_dims(uint8_t * arg) {
  onnx_runtime_impl_list_u64_t ret;
  exports_cosmonic_onnx_runtime_types_method_tensor_get_dims(((exports_cosmonic_onnx_runtime_types_tensor_t*) arg), &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("cosmonic:onnx-runtime/types#[method]tensor.get-data")))
uint8_t * __wasm_export_exports_cosmonic_onnx_runtime_types_method_tensor_get_data(uint8_t * arg, int32_t arg0, int32_t arg1) {
  onnx_runtime_impl_option_bool_t option;
  switch (arg0) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = arg1;
      break;
    }
  }
  onnx_runtime_impl_list_u8_t ret;
  exports_cosmonic_onnx_runtime_types_method_tensor_get_data(((exports_cosmonic_onnx_runtime_types_tensor_t*) arg), option.is_some ? &(option.val) : NULL, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_onnx_runtime_impl(void);
__attribute__((used))
void __component_type_object_force_link_onnx_runtime_impl_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_onnx_runtime_impl();
}
