// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#ifndef __BINDINGS_ONNX_RUNTIME_IMPL_H
#define __BINDINGS_ONNX_RUNTIME_IMPL_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct onnx_runtime_impl_string_t {
  uint8_t*ptr;
  size_t len;
} onnx_runtime_impl_string_t;

// TODO: remove
typedef onnx_runtime_impl_string_t exports_cosmonic_onnx_runtime_types_error_t;

// Graph optimization level
typedef uint8_t exports_cosmonic_onnx_runtime_types_graph_optimization_level_t;

#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_GRAPH_OPTIMIZATION_LEVEL_DISABLED 0
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_GRAPH_OPTIMIZATION_LEVEL_BASIC 1
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_GRAPH_OPTIMIZATION_LEVEL_EXTENDED 2
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_GRAPH_OPTIMIZATION_LEVEL_LAYOUT 3
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_GRAPH_OPTIMIZATION_LEVEL_ALL 4

typedef struct {
  bool is_some;
  exports_cosmonic_onnx_runtime_types_graph_optimization_level_t val;
} exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_t;

// Session options for creating an inference session
typedef struct exports_cosmonic_onnx_runtime_types_session_options_t {
  // Execution providers
  // execution-providers: option<list<execution-provider-config>>,
  // /// Thread configuration
  // TODO: probably hard code to 1 for now
  // intra-op-num-threads: option<u32>,
  // inter-op-num-threads: option<u32>,
  // /// Free dimension overrides
  // free-dimension-overrides: option<map<string, u64>>,
  // Optimization settings
  exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_t   graph_optimization_level;
} exports_cosmonic_onnx_runtime_types_session_options_t;

typedef uint8_t exports_cosmonic_onnx_runtime_types_log_severity_level_t;

#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_LOG_SEVERITY_LEVEL_VERBOSE 0
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_LOG_SEVERITY_LEVEL_INFO 1
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_LOG_SEVERITY_LEVEL_WARNING 2
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_LOG_SEVERITY_LEVEL_ERROR 3
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_LOG_SEVERITY_LEVEL_FATAL 4

typedef struct {
  bool is_some;
  exports_cosmonic_onnx_runtime_types_log_severity_level_t val;
} exports_cosmonic_onnx_runtime_types_option_log_severity_level_t;

typedef struct {
  bool is_some;
  uint32_t val;
} onnx_runtime_impl_option_u32_t;

typedef struct {
  bool is_some;
  bool val;
} onnx_runtime_impl_option_bool_t;

typedef struct {
  bool is_some;
  onnx_runtime_impl_string_t val;
} onnx_runtime_impl_option_string_t;

typedef struct {
  onnx_runtime_impl_string_t f0;
  onnx_runtime_impl_string_t f1;
} onnx_runtime_impl_tuple2_string_string_t;

typedef struct {
  onnx_runtime_impl_tuple2_string_string_t *ptr;
  size_t len;
} onnx_runtime_impl_list_tuple2_string_string_t;

typedef struct exports_cosmonic_onnx_runtime_types_run_options_t {
  exports_cosmonic_onnx_runtime_types_option_log_severity_level_t   log_severity_level;
  onnx_runtime_impl_option_u32_t   log_verbosity_level;
  onnx_runtime_impl_option_bool_t   terminate;
  onnx_runtime_impl_option_string_t   tag;
  // extra: option<map<string, string>>,
  onnx_runtime_impl_list_tuple2_string_string_t   extra;
} exports_cosmonic_onnx_runtime_types_run_options_t;

typedef struct exports_cosmonic_onnx_runtime_types_own_session_t {
  int32_t __handle;
} exports_cosmonic_onnx_runtime_types_own_session_t;

typedef struct exports_cosmonic_onnx_runtime_types_session_t exports_cosmonic_onnx_runtime_types_session_t;

typedef exports_cosmonic_onnx_runtime_types_session_t* exports_cosmonic_onnx_runtime_types_borrow_session_t;

// Tensor data types
typedef uint8_t exports_cosmonic_onnx_runtime_types_tensor_type_t;

#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_FLOAT32 0
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_UINT8 1
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_INT8 2
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_UINT16 3
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_INT16 4
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_INT32 5
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_INT64 6
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_STRING 7
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_BOOL 8
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_FLOAT16 9
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_FLOAT64 10
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_UINT32 11
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_UINT64 12
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_UINT4 13
#define EXPORTS_COSMONIC_ONNX_RUNTIME_TYPES_TENSOR_TYPE_INT4 14

typedef struct exports_cosmonic_onnx_runtime_types_own_tensor_t {
  int32_t __handle;
} exports_cosmonic_onnx_runtime_types_own_tensor_t;

typedef struct exports_cosmonic_onnx_runtime_types_tensor_t exports_cosmonic_onnx_runtime_types_tensor_t;

typedef exports_cosmonic_onnx_runtime_types_tensor_t* exports_cosmonic_onnx_runtime_types_borrow_tensor_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} onnx_runtime_impl_list_u8_t;

typedef struct {
  bool is_some;
  exports_cosmonic_onnx_runtime_types_session_options_t val;
} exports_cosmonic_onnx_runtime_types_option_session_options_t;

typedef struct {
  bool is_err;
  union {
    exports_cosmonic_onnx_runtime_types_own_session_t ok;
    exports_cosmonic_onnx_runtime_types_error_t err;
  } val;
} exports_cosmonic_onnx_runtime_types_result_own_session_error_t;

typedef struct {
  onnx_runtime_impl_string_t f0;
  exports_cosmonic_onnx_runtime_types_own_tensor_t f1;
} exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_t;

typedef struct {
  exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_t *ptr;
  size_t len;
} exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t;

typedef struct {
  bool is_some;
  exports_cosmonic_onnx_runtime_types_run_options_t val;
} exports_cosmonic_onnx_runtime_types_option_run_options_t;

typedef struct {
  bool is_err;
  union {
    exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t ok;
    exports_cosmonic_onnx_runtime_types_error_t err;
  } val;
} exports_cosmonic_onnx_runtime_types_result_list_tuple2_string_own_tensor_error_t;

typedef struct {
  uint64_t *ptr;
  size_t len;
} onnx_runtime_impl_list_u64_t;

typedef struct {
  bool is_err;
  union {
    exports_cosmonic_onnx_runtime_types_own_tensor_t ok;
    exports_cosmonic_onnx_runtime_types_error_t err;
  } val;
} exports_cosmonic_onnx_runtime_types_result_own_tensor_error_t;

// Exported Functions from `cosmonic:onnx-runtime/types`
bool exports_cosmonic_onnx_runtime_types_create_session(onnx_runtime_impl_list_u8_t *model_data, exports_cosmonic_onnx_runtime_types_session_options_t *maybe_options, exports_cosmonic_onnx_runtime_types_own_session_t *ret, exports_cosmonic_onnx_runtime_types_error_t *err);
bool exports_cosmonic_onnx_runtime_types_method_session_run(exports_cosmonic_onnx_runtime_types_borrow_session_t self, exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t *feeds, exports_cosmonic_onnx_runtime_types_run_options_t *maybe_options, exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t *ret, exports_cosmonic_onnx_runtime_types_error_t *err);
bool exports_cosmonic_onnx_runtime_types_create_tensor(exports_cosmonic_onnx_runtime_types_tensor_type_t type, onnx_runtime_impl_list_u8_t *data, onnx_runtime_impl_list_u64_t *dims, exports_cosmonic_onnx_runtime_types_own_tensor_t *ret, exports_cosmonic_onnx_runtime_types_error_t *err);
void exports_cosmonic_onnx_runtime_types_method_tensor_get_dims(exports_cosmonic_onnx_runtime_types_borrow_tensor_t self, onnx_runtime_impl_list_u64_t *ret);
void exports_cosmonic_onnx_runtime_types_method_tensor_get_data(exports_cosmonic_onnx_runtime_types_borrow_tensor_t self, bool *maybe_release_data, onnx_runtime_impl_list_u8_t *ret);

// Helper Functions

void exports_cosmonic_onnx_runtime_types_error_free(exports_cosmonic_onnx_runtime_types_error_t *ptr);

void exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_free(exports_cosmonic_onnx_runtime_types_option_graph_optimization_level_t *ptr);

void exports_cosmonic_onnx_runtime_types_session_options_free(exports_cosmonic_onnx_runtime_types_session_options_t *ptr);

void exports_cosmonic_onnx_runtime_types_option_log_severity_level_free(exports_cosmonic_onnx_runtime_types_option_log_severity_level_t *ptr);

void onnx_runtime_impl_option_u32_free(onnx_runtime_impl_option_u32_t *ptr);

void onnx_runtime_impl_option_bool_free(onnx_runtime_impl_option_bool_t *ptr);

void onnx_runtime_impl_option_string_free(onnx_runtime_impl_option_string_t *ptr);

void onnx_runtime_impl_tuple2_string_string_free(onnx_runtime_impl_tuple2_string_string_t *ptr);

void onnx_runtime_impl_list_tuple2_string_string_free(onnx_runtime_impl_list_tuple2_string_string_t *ptr);

void exports_cosmonic_onnx_runtime_types_run_options_free(exports_cosmonic_onnx_runtime_types_run_options_t *ptr);

extern void exports_cosmonic_onnx_runtime_types_session_drop_own(exports_cosmonic_onnx_runtime_types_own_session_t handle);

extern exports_cosmonic_onnx_runtime_types_own_session_t exports_cosmonic_onnx_runtime_types_session_new(exports_cosmonic_onnx_runtime_types_session_t *rep);
extern exports_cosmonic_onnx_runtime_types_session_t* exports_cosmonic_onnx_runtime_types_session_rep(exports_cosmonic_onnx_runtime_types_own_session_t handle);
void exports_cosmonic_onnx_runtime_types_session_destructor(exports_cosmonic_onnx_runtime_types_session_t *rep);

extern void exports_cosmonic_onnx_runtime_types_tensor_drop_own(exports_cosmonic_onnx_runtime_types_own_tensor_t handle);

extern exports_cosmonic_onnx_runtime_types_own_tensor_t exports_cosmonic_onnx_runtime_types_tensor_new(exports_cosmonic_onnx_runtime_types_tensor_t *rep);
extern exports_cosmonic_onnx_runtime_types_tensor_t* exports_cosmonic_onnx_runtime_types_tensor_rep(exports_cosmonic_onnx_runtime_types_own_tensor_t handle);
void exports_cosmonic_onnx_runtime_types_tensor_destructor(exports_cosmonic_onnx_runtime_types_tensor_t *rep);

void onnx_runtime_impl_list_u8_free(onnx_runtime_impl_list_u8_t *ptr);

void exports_cosmonic_onnx_runtime_types_option_session_options_free(exports_cosmonic_onnx_runtime_types_option_session_options_t *ptr);

void exports_cosmonic_onnx_runtime_types_result_own_session_error_free(exports_cosmonic_onnx_runtime_types_result_own_session_error_t *ptr);

void exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_free(exports_cosmonic_onnx_runtime_types_tuple2_string_own_tensor_t *ptr);

void exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_free(exports_cosmonic_onnx_runtime_types_list_tuple2_string_own_tensor_t *ptr);

void exports_cosmonic_onnx_runtime_types_option_run_options_free(exports_cosmonic_onnx_runtime_types_option_run_options_t *ptr);

void exports_cosmonic_onnx_runtime_types_result_list_tuple2_string_own_tensor_error_free(exports_cosmonic_onnx_runtime_types_result_list_tuple2_string_own_tensor_error_t *ptr);

void onnx_runtime_impl_list_u64_free(onnx_runtime_impl_list_u64_t *ptr);

void exports_cosmonic_onnx_runtime_types_result_own_tensor_error_free(exports_cosmonic_onnx_runtime_types_result_own_tensor_error_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void onnx_runtime_impl_string_set(onnx_runtime_impl_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void onnx_runtime_impl_string_dup(onnx_runtime_impl_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void onnx_runtime_impl_string_free(onnx_runtime_impl_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
